version: '3.4'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  backend:
    image: mealdiaries
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run start
volumes:
  mongo-data:
