version: '3.4'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run dev
volumes:
  mongo-data:
