name: Docker Hub

on:
  workflow_run:
    workflows: [ "Node.js CI" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build using compose file
      run: docker compose build -t mealdiaries
    
    - name: Tag the image
      run: |
        docker tag mealdiaries ${{ secrets.DOCKER_USERNAME }}/mealdiaries:latest 
        docker tag mealdiaries ${{ secrets.DOCKER_USERNAME }}/mealdiaries:${{ github.run_number }}
    
    - name: Push the image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mealdiaries:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mealdiaries:${{ github.run_number }}
