name: Heroku Deploy

on:
  workflow_run:
    workflows: [ "Node.js CI" ]
    branches: [ "main" ]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: "${{ secrets.HEROKU_API }}"
        heroku_email: "salmanadhikari415@gmail.com"
        heroku_app_name: "mealdiaries"
        
